name: Embed examples into README

on:
  push:
    branches:    
      - '**'  # matches every branch

jobs:
  auto-update-readme: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_message: Update README.md
          output_file_paths: '[./README.md]'
          categories: '[code-block]'